### ISSUE TITLE
Uncaught ReferenceError: MIDIFileHeader is not defined

### ISSUE THREAD

**Issue by alijaya** [nfroidure/MIDIFile#23]
Hello, I get this error when I try run the sample code from the readme. I use the dist version.

**Comment by nfroidure** [comment]
Hi @alijaya . According to the README sample, it is normal. The MidiFileHeader constructor is not defined as a global variable. It is exporter as a `MIDIFile.Header` property (https://github.com/nfroidure/MIDIFile/blob/master/src/MIDIFile.js#L313) so replacing it by that one should make it work. Can you check ?

Leaving the issue open since the README should be patched. Feel free to PR if you got some time, otherwise will do when I'll have some time to.

**Comment by nfroidure** [comment]
https://github.com/nfroidure/MIDIFile/pull/24

**Comment by alijaya** [comment]
Ah yes, it works... thanks :D
